### PR TITLE
Fixes for Mac issues

### PR DESCRIPTION
**Pull request by robryk**
This should fix various build problems on Mac (#39 and #41).

### CODE REVIEW

**Comment by pornel** [comment]
There's no `libgflags`. The package is called `gflags`

`libpng` works though.

```sh
pkg-config --libs libpng gflags

**Comment by robryk** [comment]
Oh gosh; even this is not consistent between environments (on my Ubuntu it's the exact reverse: there is `libgflags.pc` but not `gflags.pc`).

**Comment by pornel** [comment]
Ahh, joys of C dependencies :)

This works for me on macOS:

```sh
pkg-config --silence-errors --libs libgflags || pkg-config --libs gflags
```

**Comment by robryk** [comment]
Ah, thanks, that's better than specifying both with `--silence-errors`.

**Pull request merged**
