### PR TITLE
Reject JPEGs with unexpectedly large coefficient values.

### PR DESCRIPTION
**Pull request by robryk**
Large coefficient values usually imply that pixel values will be
clipped, so we will be trying to optimize a suboptimal representation of
the image. Also, handling of very large coefficient values is rife with
problems (overflows when handling unwuantized values, inability to
encode at some quantization levels, etc.).

Fixes oss-fuzz/970 and oss-fuzz/971.

### CODE REVIEW

**Comment by robryk** [comment]
PTAL.

**Comment by pornel** [comment]
BTW, clipping of pixel values is useful and can improve quality: https://kornel.ski/deringing/

**Comment by robryk** [comment]
Thanks for the correction: the commit message is wrong, but it's too late to change it now. There are clipped representations that are more efficient than ones that avoid clipping and there can also be such that are much worse. Guetzli doesn't understand how to use clipping -- when faced with a JPEG input it will try to preserve most coefficients. Thus it will perform well on an original representation with well chosen clipping, and poorly on an input with badly chosen clipping.

This change doesn't reject JPEGs that have any clipping, only JPEGs that have such abnormally high coefficients that virtually certainly there's lots of clipping going on. The main reason for this change is to avoid problems with dealing with coefficients close to overflow (e.g. ones that cannot be represented at quantization level 1 at all).

Do you expect that this change might affect files with optimized clipping?

**Comment by pornel** [comment]
I'm not sure what maximum magnitude the deringing trick can produce. It limits values of pixels in YUV space (allows overshoot from 255-272 IIRC), but doesn't do anything for ACs. libjpeg-turbo had to add extra check in their 16-bit SIMD-optimized code to prevent overflows, but that's not necessarily due to individual AC's exceeding that.

So I don't know. Probably not?

**Pull request merged**
