### PR TITLE
Add CUDA & OpenCL support

### PR DESCRIPTION
**Pull request by crazyks**
Recreate a pull [#227](https://github.com/google/guetzli/pull/227).

### CODE REVIEW

**Comment by pornel** [comment]
Hi @crazyks! That's an awesome functionality.

But this pull request contains more than 250 new files! There is a lot of new files in `third_party` folder, including libjpeg, zlib, and binary files. That's probably not intentional? Could you delete these and squash or fixup the commits?

**Comment by crazyks** [comment]
Thanks for your reply. We will remove some redundant files:)发自我的iPhone------------------ Original ------------------From: Kornel  <notifications@github.com>Date: 周一,7月 10,2017 22:11To: google/guetzli <guetzli@noreply.github.com>Cc: Zhou Ke <crazyks@yeah.net>, Mention <mention@noreply.github.com>Subject: Re: [google/guetzli] Add CUDA & OpenCL support (#223)Hi @crazyks! That's an awesome functionality.
But this pull request contains more than 250 new files! There is a lot of new files in third_party folder, including libjpeg, zlib, and binary files. That's probably not intentional? Could you delete these and squash or fixup the commits?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/google/guetzli","title":"google/guetzli","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/google/guetzli"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pornel in #223: Hi @crazyks! That's an awesome functionality.\r\n\r\nBut this pull request contains more than 250 new files! There is a lot of new files in `third_party` folder, including libjpeg, zlib, and binary files. That's probably not intentional? Could you delete these and squash or fixup the commits?\r\n"}],"action":{"name":"View Pull Request","url":"https://github.com/google/guetzli/pull/223#issuecomment-314117542"}}}

**Comment by crazyks** [comment]
We signed the CLA

**Comment by crazyks** [comment]
update CLA

**Comment by ianhuang-777** [comment]
I signed it!

**Comment by rogierlommers** [comment]
So any e.t.a. about when we can get a new (official) release which supports CUDA & OpenCL?

**Pull request closed without merging**
